name: flutter_pacman
description: Cloning the PacMan game with Flutter!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flame: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: 8BitMadness
      fonts:
        - asset: assets/fonts/8_bit_madness.ttf

  assets:
    - assets/images/wall/wall_down_close_left.png
    - assets/images/wall/wall_down_close_right.png
    - assets/images/wall/wall_down.png
    - assets/images/wall/wall_side_bottom_left.png
    - assets/images/wall/wall_side_bottom_right.png
    - assets/images/wall/wall_side_top_left.png
    - assets/images/wall/wall_side_top_right.png
    - assets/images/wall/wall_up_close_bottom.png
    - assets/images/wall/wall_up_close_top.png
    - assets/images/wall/wall_up.png
    - assets/images/ground.png
    - assets/images/coin.png
    - assets/images/pacman/pacman_idle.png
    - assets/images/enemies/ghosts/ghost_blue.png
    - assets/images/enemies/ghosts/ghost_green.png
    - assets/images/enemies/ghosts/ghost_light_green.png
    - assets/images/enemies/ghosts/ghost_light_blue.png
    - assets/images/enemies/ghosts/ghost_pink.png
    - assets/images/enemies/ghosts/ghost_red.png
